CREATE TABLE "ethnic_groups" (
	"id" serial PRIMARY KEY NOT NULL,
	"slug" text NOT NULL,
	"name" text NOT NULL,
	"autonym" text,
	"countries" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"continent" text DEFAULT '' NOT NULL,
	"regions" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"cities" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"languages" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"language_family" text,
	"language_subfamily" text,
	"glottolog_urls" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"summary" text DEFAULT '' NOT NULL,
	"lat" double precision,
	"lng" double precision,
	"zoom" integer,
	"geojson" text,
	"image_url" text,
	"updated_at" integer DEFAULT extract(epoch from now())::integer NOT NULL,
	CONSTRAINT "ethnic_groups_slug_unique" UNIQUE("slug")
);
